steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/my-projec-250724/demo-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/my-projec-250724/demo-app"]

images:
  - "gcr.io/my-projec-250724/demo-app"

options:
  logging: CLOUD_LOGGING_ONLY
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-app']
images:
  - 'gcr.io/gcp-study-463918/demo-app'
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-app']
images:
  - 'gcr.io/gcp-study-463918/demo-app'
options:
  logging: CLOUD_LOGGING_ONLY    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-app']
images:
  - 'gcr.io/gcp-study-463918/demo-app'
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-app']
images:
  - 'gcr.io/gcp-study-463918/demo-app'
options:
  logging: CLOUD_LOGGING_ONLY


